version: "3.8"

services:
  postgres:
    image: postgres:17-alpine
    container_name: assistant-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-assistant}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-assistant_password}
      POSTGRES_DB: ${POSTGRES_DB:-assistant_dev}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-assistant}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
    driver: local
